### ISSUE TITLE
Grayscale PNG image flags are incorrect

### ISSUE THREAD

**Issue by hughbe** [mono/libgdiplus#184]
In `testpngcodec.c`

```cpp
#define createFileSuccess(buffer, format, width, height, flags, propertyCount) \
{ \
	createFile (buffer, Ok); \
	/* FIXME: grayscale image flags are incorrect. */ \
	verifyImage (image, ImageTypeBitmap, pngRawFormat, format, 0, 0, width, height, (REAL) width, (REAL) height, flags, propertyCount, FALSE); \
	GdipDisposeImage (image); \
}
```

**Comment by filipnavara** [comment]
Can be closed I guess.

**Comment by filipnavara** [comment]
I may have rushed a bit with closing this, but there are issues with the tests themselves:

- The test for combination of 4 bits per pixel and grayscale with alpha channel is in function `test_valid4bpp`. According to PNG specification this is invalid: http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html
- Most of the other case of different flags are due to missing up-conversion to 32-bit ARGB. While the pixel format is checked for different format based on the `USE_WINDOWS_GDIPLUS` definition, the flags are not and differ by `ImageFlagsHasAlpha`.
- The last difference is that libgdiplus report 1-bpp Grayscale images as ImageFlagsColorSpaceGRAY, while gdiplus.dll reports it as ImageFlagsColorSpaceRGB.

Most likely Microsoft decided to upconvert all the grayscale images to 32-bit ARGB with the exception of 1-bpp ones that are used for masks.

**Comment by akoeplinger** [comment]
Let's reopen then :)
